### ISSUE TITLE
TODO-list for v1.0

### ISSUE THREAD

**Issue by cpascual** [cpascual/peakevo#1]
- [ ] use deltatime instead of absolute.
- [ ] remove button removes all selected
- [ ] button for exporting the series plot
- [ ] Auto save series data while on record (append time, lambda pairs)
- [ ] disable acq time control once background or ref are set
- [ ] show name of bkg and ref. Use checkable buttons (allowing to uncheck)
- [ ] store time acq and filenames for ref and bkg on each file
- [ ] make button for choosing output dir work
- [ ] store settings and retrieve on start
- [ ] highlight series points points when selecting on list
